// <auto-generated />
namespace Team_5_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class whydoineedamigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whydoineedamigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201712070413310_whydoineedamigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
