// <auto-generated />
namespace Team_5_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class primarytravelerid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primarytravelerid));
        
        string IMigrationMetadata.Id
        {
            get { return "201712050116596_primarytravelerid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
